### ISSUE TITLE
Error at Block Height 65084 (bank exited due to signal SIGSEGV)

### ISSUE THREAD

**Issue by Blockproduction** [Agoric/testnet-notes#9]
```
2021-05-14T03:06:13.695Z block-manager: block 65084 begin
3:06AM INF Starting Peer service impl="Peer{MConn{178.128.51.171:26656} d0529494b41949f4d14cd4269d19a72f9c50c443 out}" module=p2p peer={"id":"d0529494b41949f4d14cd4269d19a72f9c50c443","ip":"178.128.51.171","port":26656}
3:06AM INF Starting MConnection service impl=MConn{178.128.51.171:26656} module=p2p peer={"id":"d0529494b41949f4d14cd4269d19a72f9c50c443","ip":"178.128.51.171","port":26656}
3:06AM INF Added peer module=p2p peer={"Data":{},"Logger":{}}
3:06AM INF Connection is closed @ recvRoutine (likely by the other side) conn={"Logger":{}} module=p2p peer={"id":"d0529494b41949f4d14cd4269d19a72f9c50c443","ip":"178.128.51.171","port":26656}
3:06AM INF Stopping MConnection service impl={"Logger":{}} module=p2p peer={"id":"d0529494b41949f4d14cd4269d19a72f9c50c443","ip":"178.128.51.171","port":26656}
3:06AM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{}}
3:06AM INF Stopping Peer service impl={"Data":{},"Logger":{}} module=p2p peer={"id":"d0529494b41949f4d14cd4269d19a72f9c50c443","ip":"178.128.51.171","port":26656}
3:06AM INF Reconnecting to peer addr={"id":"d0529494b41949f4d14cd4269d19a72f9c50c443","ip":"178.128.51.171","port":26656} module=p2p
3:06AM INF Dialing peer address={"id":"d0529494b41949f4d14cd4269d19a72f9c50c443","ip":"178.128.51.171","port":26656} module=p2p
3:06AM INF Stopping gossipVotesRoutine for peer module=consensus peer={"Data":{},"Logger":{}}
3:06AM INF Stopping gossipDataRoutine for peer module=consensus peer={"Data":{},"Logger":{}}
3:06AM INF Starting Peer service impl="Peer{MConn{13.250.244.198:26656} d43e199470a741f99949b78bf963c03ec2079373 out}" module=p2p peer={"id":"d43e199470a741f99949b78bf963c03ec2079373","ip":"13.250.244.198","port":26656}
3:06AM INF Starting MConnection service impl=MConn{13.250.244.198:26656} module=p2p peer={"id":"d43e199470a741f99949b78bf963c03ec2079373","ip":"13.250.244.198","port":26656}
3:06AM INF Added peer module=p2p peer={"Data":{},"Logger":{}}
3:06AM INF Connection is closed @ recvRoutine (likely by the other side) conn={"Logger":{}} module=p2p peer={"id":"d43e199470a741f99949b78bf963c03ec2079373","ip":"13.250.244.198","port":26656}
3:06AM INF Stopping MConnection service impl={"Logger":{}} module=p2p peer={"id":"d43e199470a741f99949b78bf963c03ec2079373","ip":"13.250.244.198","port":26656}
3:06AM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{}}
3:06AM INF Stopping Peer service impl={"Data":{},"Logger":{}} module=p2p peer={"id":"d43e199470a741f99949b78bf963c03ec2079373","ip":"13.250.244.198","port":26656}
3:06AM INF Stopping gossipVotesRoutine for peer module=consensus peer={"Data":{},"Logger":{}}
3:06AM INF Stopping gossipDataRoutine for peer module=consensus peer={"Data":{},"Logger":{}}
3:06AM INF Stopping queryMaj23Routine for peer module=consensus peer={"Data":{},"Logger":{}}
2021-05-14T03:06:14.207Z SwingSet: kernel: SwingSet:vatWorker IBC downcall bindPort { packet: { source_port: 'port-133' } }
3:06AM INF created new capability module=ibc name=ports/port-133
3:06AM INF port binded module=x/ibc/port port=port-133
3:06AM INF claimed capability capability=136 module=dibc name=ports/port-133
3:06AM ERR dialing failed (attempts: 10): dial tcp 135.181.105.129:26656: i/o timeout addr={"id":"7c7d50c84033107ec0c67bc2181716b68519e724","ip":"135.181.105.129","port":26656} module=pex
3:06AM ERR dialing failed (attempts: 11): dial tcp 35.175.206.227:26656: i/o timeout addr={"id":"b61a25f419fcade6770aba0bdbd19e980b27200f","ip":"35.175.206.227","port":26656} module=pex
3:06AM INF Starting Peer service impl="Peer{MConn{178.128.51.171:26656} d0529494b41949f4d14cd4269d19a72f9c50c443 out}" module=p2p peer={"id":"d0529494b41949f4d14cd4269d19a72f9c50c443","ip":"178.128.51.171","port":26656}
3:06AM INF Starting MConnection service impl=MConn{178.128.51.171:26656} module=p2p peer={"id":"d0529494b41949f4d14cd4269d19a72f9c50c443","ip":"178.128.51.171","port":26656}
3:06AM INF Added peer module=p2p peer={"Data":{},"Logger":{}}
3:06AM INF Connection is closed @ recvRoutine (likely by the other side) conn={"Logger":{}} module=p2p peer={"id":"d0529494b41949f4d14cd4269d19a72f9c50c443","ip":"178.128.51.171","port":26656}
3:06AM INF Stopping MConnection service impl={"Logger":{}} module=p2p peer={"id":"d0529494b41949f4d14cd4269d19a72f9c50c443","ip":"178.128.51.171","port":26656}
3:06AM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{}}
3:06AM INF Stopping Peer service impl={"Data":{},"Logger":{}} module=p2p peer={"id":"d0529494b41949f4d14cd4269d19a72f9c50c443","ip":"178.128.51.171","port":26656}
3:06AM INF Reconnecting to peer addr={"id":"d0529494b41949f4d14cd4269d19a72f9c50c443","ip":"178.128.51.171","port":26656} module=p2p
3:06AM INF Dialing peer address={"id":"d0529494b41949f4d14cd4269d19a72f9c50c443","ip":"178.128.51.171","port":26656} module=p2p
2021-05-14T03:06:14.535Z SwingSet: kernel: SwingSet:vatWorker IBC downcall bindPort { packet: { source_port: 'port-134' } }
3:06AM INF created new capability module=ibc name=ports/port-134
3:06AM INF port binded module=x/ibc/port port=port-134
3:06AM INF claimed capability capability=137 module=dibc name=ports/port-134
3:06AM INF Stopping gossipVotesRoutine for peer module=consensus peer={"Data":{},"Logger":{}}
3:06AM INF Stopping gossipDataRoutine for peer module=consensus peer={"Data":{},"Logger":{}}
2021-05-14T03:06:14.939Z SwingSet: kernel: SwingSet:vatWorker IBC downcall bindPort { packet: { source_port: 'port-135' } }
3:06AM INF Stopping queryMaj23Routine for peer module=consensus peer={"Data":{},"Logger":{}}
3:06AM INF created new capability module=ibc name=ports/port-135
3:06AM INF port binded module=x/ibc/port port=port-135
3:06AM INF claimed capability capability=138 module=dibc name=ports/port-135
3:06AM INF Starting Peer service impl="Peer{MConn{178.128.51.171:26656} d0529494b41949f4d14cd4269d19a72f9c50c443 out}" module=p2p peer={"id":"d0529494b41949f4d14cd4269d19a72f9c50c443","ip":"178.128.51.171","port":26656}
3:06AM INF Starting MConnection service impl=MConn{178.128.51.171:26656} module=p2p peer={"id":"d0529494b41949f4d14cd4269d19a72f9c50c443","ip":"178.128.51.171","port":26656}
3:06AM INF Added peer module=p2p peer={"Data":{},"Logger":{}}
3:06AM INF Connection is closed @ recvRoutine (likely by the other side) conn={"Logger":{}} module=p2p peer={"id":"d0529494b41949f4d14cd4269d19a72f9c50c443","ip":"178.128.51.171","port":26656}
3:06AM INF Stopping MConnection service impl={"Logger":{}} module=p2p peer={"id":"d0529494b41949f4d14cd4269d19a72f9c50c443","ip":"178.128.51.171","port":26656}
3:06AM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{}}
3:06AM INF Stopping Peer service impl={"Data":{},"Logger":{}} module=p2p peer={"id":"d0529494b41949f4d14cd4269d19a72f9c50c443","ip":"178.128.51.171","port":26656}
3:06AM INF Reconnecting to peer addr={"id":"d0529494b41949f4d14cd4269d19a72f9c50c443","ip":"178.128.51.171","port":26656} module=p2p
3:06AM INF Dialing peer address={"id":"d0529494b41949f4d14cd4269d19a72f9c50c443","ip":"178.128.51.171","port":26656} module=p2p
3:06AM INF Stopping gossipDataRoutine for peer module=consensus peer={"Data":{},"Logger":{}}
3:06AM INF Stopping gossipVotesRoutine for peer module=consensus peer={"Data":{},"Logger":{}}
3:06AM INF Stopping queryMaj23Routine for peer module=consensus peer={"Data":{},"Logger":{}}
3:06AM INF Stopping queryMaj23Routine for peer module=consensus peer={"Data":{},"Logger":{}}
3:06AM INF Starting Peer service impl="Peer{MConn{178.128.51.171:26656} d0529494b41949f4d14cd4269d19a72f9c50c443 out}" module=p2p peer={"id":"d0529494b41949f4d14cd4269d19a72f9c50c443","ip":"178.128.51.171","port":26656}
3:06AM INF Starting MConnection service impl=MConn{178.128.51.171:26656} module=p2p peer={"id":"d0529494b41949f4d14cd4269d19a72f9c50c443","ip":"178.128.51.171","port":26656}
3:06AM INF Connection is closed @ recvRoutine (likely by the other side) conn={"Logger":{}} module=p2p peer={"id":"d0529494b41949f4d14cd4269d19a72f9c50c443","ip":"178.128.51.171","port":26656}
3:06AM INF Stopping MConnection service impl={"Logger":{}} module=p2p peer={"id":"d0529494b41949f4d14cd4269d19a72f9c50c443","ip":"178.128.51.171","port":26656}
3:06AM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{}}
3:06AM INF Stopping Peer service impl={"Data":{},"Logger":{}} module=p2p peer={"id":"d0529494b41949f4d14cd4269d19a72f9c50c443","ip":"178.128.51.171","port":26656}
3:06AM INF Stopping queryMaj23Routine for peer module=consensus peer={"Data":{},"Logger":{}}
3:06AM INF Stopping gossipVotesRoutine for peer module=consensus peer={"Data":{},"Logger":{}}
3:06AM INF Added peer module=p2p peer={"Data":{},"Logger":{}}
3:06AM INF Stopping gossipDataRoutine for peer module=consensus peer={"Data":{},"Logger":{}}
3:06AM INF Stopping queryMaj23Routine for peer module=consensus peer={"Data":{},"Logger":{}}
2021-05-14T03:06:16.503Z SwingSet: kernel: problem terminating vat v1 (ExitSignal#1)
ExitSignal#1: v1:bank exited due to signal SIGSEGV

  at new ErrorSignal (packages/xsnap/api.js:37:5)
  at ChildProcess.<anonymous> (packages/xsnap/src/xsnap.js:116:22)
  at ChildProcess.emit (events.js:314:20)
  at ChildProcess.EventEmitter.emit (domain.js:483:12)

3:06AM INF Stopping queryMaj23Routine for peer module=consensus peer={"Data":{},"Logger":{}}
Logging sent error stack (RemoteError#3)
RemoteError#3: vat terminated
Error: vat terminated
 at construct (0:0)
 at Error (0:0)
 at makeError (0:0)
 at fullRevive (0:0)
 at unserialize (0:0)
 at notifyOnePromise (0:0)
 at notify (0:0)
 at dispatchToUserspace (0:0)
 at (0:0)

RemoteError#3 ERROR_NOTE: Rejection from: (Error#4) : 2155 . 0
RemoteError#3 ERROR_NOTE: Rejection from: (Error#5) : 2147 . 1
RemoteError#3 ERROR_NOTE: Sent as error:liveSlots:v12#70001
Error#4: Event: 2154.1
Error: Event: 2154.1
 at construct (0:0)
 at Error (0:0)
 at trackTurns (0:0)
 at handle (0:0)
 at (0:0)
 at createUserBundle (0:0)
 at (0:0)
 at (0:-1843544592)

Error#5: Event: 2146.1
Error: Event: 2146.1
 at construct (0:0)
 at Error (0:0)
 at trackTurns (0:0)
 at handle (0:0)
 at deliver (0:0)
 at dispatchToUserspace (0:0)
 at (0:0)

3:06AM INF executed block height=65084 module=state num_invalid_txs=0 num_valid_txs=1
3:06AM INF commit synced commit=436F6D6D697449447B5B3130382035372032302031373020393220323320323337203133302031333520323131203730203137362031303020313537203537203131382031353120323533203230352032323420313035203831203535203832203130382032333920323332203134302036382032203134362033305D3A464533437D
2021-05-14T03:06:19.105Z block-manager: block 65084 commit
```

**Comment by dckc** [comment]
this is a dup of #7

for follow-up, see https://github.com/Agoric/agoric-sdk/issues/3085 phase3 testnet (act 2) killed by SIGSEGV of vat-bank worker
